In [7]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

In [8]:
# make an identity matrix of length n
arrIdentity = np.identity(2)

# make a matrix of zeroes or ones
arrZeros = np.zeros((2, 2))
arrOnes = np.ones((3, 2))

# create a matrix of random numbers
arrRandom = np.random.randn(2, 2)
arrIdentity.shape

# make a new array with range [0, 9) having shape (3, 3) 
# make sure that m X n = no. of elements in the array, i.e. 9 in this case.
arrReshape = np.arange(50).reshape(5, 10)


In [9]:
# Integer based Advanced indexing
arrIntIndexing = np.arange(9).reshape(3, 3)     # make an array of 3X3 having integers [0,9).
arrIntIndexing[[0, 1, 2], [1, 0, 0]]         # from 0,1,2 rows give respective 1,0,0 columns i.e.((0,1), (1, 0), (2, 0))

# Boolean based Advanced indexing
arrBooleanIndexing = np.random.randn(2,2)
arrBooleanIndexing[arrBooleanIndexing > 0]      # Shows only the integers that are greater than 0.

array([0.68366808])

In [10]:
# Algebraic operations on the arrays (performed by Ufuncs)
arr1 = np.arange(15).reshape(5,3)
arr2 = np.arange(5).reshape(5,1)
arr1*arr2

# dot, transpose, svd
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
b = np.array([[9, 8, 7], [6, 5, 4], [3, 2, 1]])

a.dot(b)
a.T
np.linalg.svd(a)

(array([[-0.21483724,  0.88723069,  0.40824829],
        [-0.52058739,  0.24964395, -0.81649658],
        [-0.82633754, -0.38794278,  0.40824829]]),
 array([1.68481034e+01, 1.06836951e+00, 3.33475287e-16]),
 array([[-0.47967118, -0.57236779, -0.66506441],
        [-0.77669099, -0.07568647,  0.62531805],
        [-0.40824829,  0.81649658, -0.40824829]]))

In [14]:
# we can solve system of equations using linalg.solve()
# eg.
# 7x+5y-3z = 16
# 3x-5y+2z = -8
# 5x+3y-7z = 0

# can be solved using 2 matrices : a and b
# a = coefficient Matrix
# b = constant vector matrix

a = np.array([[7, 5, -3], [3, -5, 2], [5, 3, -7]])
b = np.array([16, -8, 0])
x = np.linalg.solve(a, b)
x

array([1., 3., 2.])

In [17]:
# np.allclose(a, b) checks if a and b are equal element wise.
np.allclose(np.dot(a, x), b)

True